# Generated by Django 3.1.1 on 2020-09-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='brand_name',
            field=models.CharField(max_length=50),
        ),
    ]
